/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelfAssessmentRouteImport } from './routes/self-assessment'
import { Route as RetrospectionRouteImport } from './routes/retrospection'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EvidenceReflectionsRouteImport } from './routes/evidence-reflections'
import { Route as IndexRouteImport } from './routes/index'

const SelfAssessmentRoute = SelfAssessmentRouteImport.update({
  id: '/self-assessment',
  path: '/self-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrospectionRoute = RetrospectionRouteImport.update({
  id: '/retrospection',
  path: '/retrospection',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceReflectionsRoute = EvidenceReflectionsRouteImport.update({
  id: '/evidence-reflections',
  path: '/evidence-reflections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evidence-reflections': typeof EvidenceReflectionsRoute
  '/login': typeof LoginRoute
  '/retrospection': typeof RetrospectionRoute
  '/self-assessment': typeof SelfAssessmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evidence-reflections': typeof EvidenceReflectionsRoute
  '/login': typeof LoginRoute
  '/retrospection': typeof RetrospectionRoute
  '/self-assessment': typeof SelfAssessmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evidence-reflections': typeof EvidenceReflectionsRoute
  '/login': typeof LoginRoute
  '/retrospection': typeof RetrospectionRoute
  '/self-assessment': typeof SelfAssessmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evidence-reflections'
    | '/login'
    | '/retrospection'
    | '/self-assessment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evidence-reflections'
    | '/login'
    | '/retrospection'
    | '/self-assessment'
  id:
    | '__root__'
    | '/'
    | '/evidence-reflections'
    | '/login'
    | '/retrospection'
    | '/self-assessment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvidenceReflectionsRoute: typeof EvidenceReflectionsRoute
  LoginRoute: typeof LoginRoute
  RetrospectionRoute: typeof RetrospectionRoute
  SelfAssessmentRoute: typeof SelfAssessmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/self-assessment': {
      id: '/self-assessment'
      path: '/self-assessment'
      fullPath: '/self-assessment'
      preLoaderRoute: typeof SelfAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retrospection': {
      id: '/retrospection'
      path: '/retrospection'
      fullPath: '/retrospection'
      preLoaderRoute: typeof RetrospectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence-reflections': {
      id: '/evidence-reflections'
      path: '/evidence-reflections'
      fullPath: '/evidence-reflections'
      preLoaderRoute: typeof EvidenceReflectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvidenceReflectionsRoute: EvidenceReflectionsRoute,
  LoginRoute: LoginRoute,
  RetrospectionRoute: RetrospectionRoute,
  SelfAssessmentRoute: SelfAssessmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
